buildscript {
    ext {
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21        // Твоя цель — Android 5.1
        compileSdkVersion = 31    // Совместимо с Gradle 7.0
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Обязательно эта версия для Gradle 7.0
        classpath("com.android.tools.build:gradle:7.0.4")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
