buildscript {
    ext {
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21        // Android 5.1 (Lollipop)
        compileSdkVersion = 31    // Android 12 (стабильно для Gradle 7)
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Плагин версии 7.0.4 строго под Gradle 7.0
        classpath("com.android.tools.build:gradle:7.0.4")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
