rootProject.name = 'telon-gateway-app'
include ':app'

def nodeModulesPath = "../node_modules"
def nativeModulesFile = new File(rootProject.projectDir, "${nodeModulesPath}/@react-native-community/cli-platform-android/native_modules.gradle")

if (nativeModulesFile.exists()) {
    apply from: nativeModulesFile
    applyNativeModulesSettingsGradle(settings)
} else {
    println "!!! ВНИМАНИЕ: Файл не найден по адресу: ${nativeModulesFile.absolutePath}"
}
