rootProject.name = 'TelonGateway'

include ':app'

// Автоматически находим папку node_modules рядом с папкой android
def nodeModulesDir = new File(rootProject.projectDir, '../node_modules')

include ':react-native-sip2'
project(':react-native-sip2').projectDir = new File(nodeModulesDir, 'react-native-sip2/android')

include ':react-native-tele'
project(':react-native-tele').projectDir = new File(nodeModulesDir, 'react-native-tele/android')

// Применяем скрипт из найденной папки
def nativeModulesScript = new File(nodeModulesDir, '@react-native-community/cli-platform-android/native_modules.gradle')
if (nativeModulesScript.exists()) {
    apply from: nativeModulesScript
    applyNativeModulesSettingsGradle(project)
}
