name: Build APK For J1 Mini
on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          cd telon-gateway-app
          # Устанавливаем зависимости. Это создаст папку node_modules внутри telon-gateway-app
          npm install --legacy-peer-deps

      - name: Check Files (Debug)
        run: |
          # Этот шаг просто покажет нам в логах, видит ли система файл native_modules.gradle
          ls -l telon-gateway-app/node_modules/@react-native-community/cli-platform-android/native_modules.gradle || echo "FILE NOT FOUND!"

      - name: Build with Gradle
        run: |
          # Заходим в папку android, которая является подпапкой telon-gateway-app
          cd telon-gateway-app/android
          chmod +x gradlew
          # Запускаем сборку
          ./gradlew assembleDebug --no-daemon -Pandroid.builder.sdkDownload=true
          
